services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
  adminer:
    image: adminer
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    ports:
      - 8080:8080
