[package]
name = "web"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
domain = { path = "../domain" }
application = { path = "../application" }
infrastructure = { path = "../infrastructure" }
tokio = { version = "1.42.0", features = ["macros", "rt-multi-thread"] }
fake = "3.1.0"
dotenvy = "0.15.7"
