[package]
name = "application"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
domain = { path = "../domain" }
async-trait = "0.1.68"
chrono = "0.4.26"
chrono-tz = "0.8.3"
