[package]
name = "infrastructure"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
domain = { path = "../domain" }
application = { path = "../application" }
sqlx = { version = "0.6.3", features = ["runtime-tokio-rustls", "postgres"] }
async-trait = "0.1.68"
ulid = "1.0.0"
