[package]
name = "infrastructure"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
domain = { path = "../domain" }
application = { path = "../application" }
sqlx = { version = "0.8.2", features = ["runtime-tokio-rustls", "postgres"] }
async-trait = "0.1.83"
jsonwebtoken = "9.3.0"
serde = { version = "1.0.216", features = ["derive"] }
chrono = "0.4.39"
chrono-tz = "0.10.0"
uuid = { version = "1.11.0", features = ["fast-rng", "v7"] }
anyhow = "1.0.95"
